# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/go/dockerfile-reference/

ARG NODE_VERSION=20.10.0

FROM node:${NODE_VERSION}-alpine

ENV NODE_ENV production

WORKDIR /usr/src/app

COPY ./server/package.json ./server/package-lock.json ./server/build  ./
# Download dependencies as a separate step to take advantage of Docker's caching.
# Leverage a cache mount to /root/.npm to speed up subsequent builds.
# Leverage a bind mounts to package.json and package-lock.json to avoid having to copy them into
# into this layer.
RUN --mount=type=bind,source=server/package.json,target=package.json \
    --mount=type=bind,source=server/package-lock.json,target=package-lock.json \
    --mount=type=bind,source=server/build,target=build \
    --mount=type=cache,target=/root/.npm


RUN npm i


# Copy the rest of the source files into the image.
COPY ./server  ./

# Expose the port that the application listens on.
EXPOSE 1208

# Run the application"
CMD ["npm" ,"start"]
